spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TomatoMall?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: yyh719119
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 8080


aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId:
    accessKeySecret:
    bucketName: tomatomall

alipay:
  app-id: 2021000147684631
  private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/nhuAPzE4Y3We4bwwpHT3fIFfsamAUZIgAY/JmZQ/sw9Po8KLuuB2MS39GxJIHwWKPLmnVkApjsY6u4avcjzY+F5xTidvy3Vkzu2e1bonUM363TteFzBVvmKHtKkAZ3RF/ecjr+Ywzm/cpQPZ9T1c+9x2Eo+sj4emSIVtkCU9G8Jy1cKAMsA1o7XCaiHKR0XZITnAmgwpD751s7yash0LgJDQekpNKThNN1/LW2ydj7rW01NzCJtIh0SQX+jLku3dsp4WMRbAG8pG2xYL0yw1akl5uM0r2iNwGc0lXwF/A0Tn7ryt/mb6uJGN7wY8zpGTQhhdS6tHUp/XQ+4gSX99AgMBAAECggEAHF0mCvzPp14pmgQmHDkryzqV1/lvcrwgWjaA90GRjUBPIuXFtXNLKJOtEAtC0IQvCMBmZtvAkaY9t5HspOnPEfrp1/HOqqC+Vta+m8VdUdaHNvwqfooGMJsG8LmQTqwBrR6haUnvVAgqzMlsYYYIuEvb3Wpv9AYm+TlA7u/oYzwHzZardz1d++IirHgxkTZ8ys32ganuysGN8Ir1eYn/sSAVsb0QqF9f5S/bOvHthF1yP2EGQxZwAaHhrvHb8HIyAyjkAg9JqoDaowpGlwqFkYcjIcVCNeQSYpjd7ldOzxBmJUMiFzdfuZCaJZ7Joy0r8K0aCfyHm4/GzZuJEFZGzQKBgQD0x7ZMlO3IriwSzGMU2JGnZAZrc1n/vaoAziExZso8vAWNlRLsEapthaUQu7HTmKsUF0I+zk3X/s0HmbCWouZ4AzA/qI/YWIczRyzmHtTxv6d/yAnu4HTnWvr2aALV7aEzYARZQAxJGFJ5FZ2HpdljgmnSgsHdNie6aRFXZgzH1wKBgQDIZpP+P0UlTrpOlE/9Jx6Rad6T8GboU9lpeJOFCn0nIqbFOPS5Q1T8HLxIY9befmOlRm8THCXY2JMEBUpBBjuA0m/QHQ5sJG7Zjf+vsW4aDY7xQPBXC/mjqw5pMX3q9S5QZgZTN6a5jg0DiaGa068WbNy9eQrOJNE3dr0dDRA4ywKBgAj2x1ZGne6bckG9+mLpC2x13UZSExmqeG9PHSgR+5X9zLZCn07F1tfr7P+P4BM/pAQ4VdS2+WLPkfKVTkI19PqwIzQxmBL0Kv9Vu+8xcdroidnEGZkF30IZstcTOAddjGm1OnOKROjoWxzUDdDJ4gwi2n07DJ5tPUc2UcxBkHZBAoGBAINVZovrXx9yFvtEi592sbvOzEXb+TUtLoDGurcoBplNRkpeZ1O64slO873lYH30Cs3X+RdnDQ6t8Ltj1CQFN53XS9vyDu+keNkvDHBSMbv1QsatLlV9zZ8Ljag2/TSsdivOkTqccDGO/MxiuHxFWquxsICkAQbUbiCROqL9WrI9AoGBALkuwNMp3g+aLrXwN8tPA/Kv23V8QSUMfZwRMwtnun26cSOO+msYebPZDhlXMZOK9u2VTqYN8XdAnGsLYIiKiBYpwLooEvu7G741Lfc9vdw7Jqneyl6b9tndV6kCveCTRu5j+na2eXzL0UCfZhLXxcBYoBQqRZvplq1G30DnynNS
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi86lI+9HxNMuPiXv/za/zotS0t/Ym+veYNIUj5gBne//vbvk8ECi6tAfQUR4e5yslU4NvsODdsBQfIswlcAJ0BQmgiVyH/ApH8WpOt1U8j5k4Uw6bhvPAQawxtJzoCnex/w2Kv4b/CBOSCrUSlNv82BDgCdDDlqkO9s/OvbQ2cWgW3LpW7oWkEyWYb/fSBkxmsvtyHPsObMiXBgR03/knTboed48jbACqYu2JZq5AYOtZ1je984Z/Wmojorgk+yBUIwt6zi/Qhamuyt2Ct+/LWU5MMnXnFYXx0z3VL39av2ol5RpkD6x+eysZwUK0uQg4QevFx+XYGF0SwDsreRMnwIDAQAB
  charset: utf-8
  sign-type: RSA2
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notify-url: http://localhost:5173/cart
  return-url: http://null